[package]
name = "pimoroni-fanshim-daemon"
version = "0.1.0"
authors = ["nbrr <nbrr@protonmail.com>"]
edition = "2021"

[dependencies]
pimoroni-fanshim = { path = "../pimoroni-fanshim" }
log = "0.4.8"
env_logger = "0.7.1"
structopt = "0.3.12"
